version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app  # монтирование локальной директории app/ в /app внутри контейнера
    image: barvv/devops-for-programmers-project-74
    command: make dev